#!/bin/sh
[ "${DEBUG_RUN:-0}" -eq 0 ] || set -x
CMD="${0##*/}"
IMGDIR="$(cd "$(dirname -- "$0")/.."; pwd -L)"
IMG="${IMGDIR##*/}"
[ -f "$IMGDIR/bin/common" ] && . "$IMGDIR/bin/common"
"$IMGDIR/../do" "$IMG" "$CMD" "$@"
